[package]
name = "comtrade_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
comtrade = { git = "https://github.com/drewsilcock/comtrade.git", rev = "ad281b6" }
